title: Horchata Cafe
description: Sweet cinnamon!
lang: en-GB
url: "https://stuartrivero.github.io"
baseurl: "/horchatacafe"

permalink: /:year/:month/:title/
timezone: Europe/London

markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
